### ISSUE TITLE
Bulk Insert and Upsert don't work

### ISSUE THREAD

**Issue by warflash** [supabase-community/postgrest-csharp#36]
# Bug Report
## Describe the bug
Bulk inserts and upserts currently don't seem to work.
The column thats labeled as primary key is inserted successfully, all other columns get set to zero values.
 
## Reproduction
Unfortunately I'm not sure how to setup the tests locally so I couldn't go and debug myself.
Though I setup a minimal example with two columns in supabase and it did not work. 
Screenshot:
![image](https://user-images.githubusercontent.com/22006082/147428205-bf10099f-8119-42df-8206-c89515bdc3a6.png)

## System Info
- OS: Windows 10 Pro
- .NET 6
- Visual Studio 17.0.4
- Versions: supabase: 0.2.11; postgrest: 2.0.3

**Comment by acupofjose** [comment]
@warflash thanks for the detailed issue! I was able to duplicate it pretty quickly and should have it resolved in `postgrest-csharp@2.0.4`. Please let me know if you see the problem persisting after updating to the latest version!

**Comment by warflash** [comment]
That fixed it indeed, thanks a lot for the quick response and update, much appreciated!
I did stumble across something else while playing around, will open a new issue for that in a bit.
Thanks again for the patch :)
