### ISSUE TITLE
QueryOptions Returning prop crashes json parser

### ISSUE THREAD

**Issue by warflash** [supabase-community/postgrest-csharp#37]
# Bug Report
## Describe the bug
QueryOptions Returning prop makes the response crash
 
## Reproduction
Setting the Returning prop in QueryOptions to "QueryOptions.ReturnType.Minimal" causes an exception while parsing the db response. 

Screenshots:
![image](https://user-images.githubusercontent.com/22006082/147432716-259821af-eed2-4a6e-8472-053af48075de.png)
![image](https://user-images.githubusercontent.com/22006082/147432705-ab21cc73-efb7-4068-8ebf-84374d7436f6.png)

## System Info
- OS: Windows 10 Pro
- .NET 6
- Visual Studio 17.0.4
- Versions: supabase: 0.2.11; postgrest: 2.0.4

**Comment by acupofjose** [comment]
@warflash this fix is available in `postgrest-csharp@2.0.5` - thanks for the bug report!
