### ISSUE TITLE
Error in README.md

### ISSUE THREAD

**Issue by kolaval** [supabase-community/postgrest-csharp#52]
# Improve documentation

## Link 

[Add a link to the page which needs improvement (if relevant)](https://github.com/supabase-community/postgrest-csharp/blob/master/README.md)

## Describe the problem

Not referencing instance

## Describe the improvement

`var client = Client.Initialize("http://localhost:3000");

    // Get All Messages
    var response = await **Client**.Table<Message>().Get();`

should be
`var response = await **client**.Table<Message>().Get();`

## Additional context

Also the code does not work it returns an Api key error.

**Comment by acupofjose** [comment]
Thanks for the catch!
