### ISSUE TITLE
Update method - no Route matched with those values

### ISSUE THREAD

**Issue by Cizzl** [supabase-community/postgrest-csharp#57]
# Bug report

## Describe the bug

I followed the instruction of the docs. When I try to use the Update method I get this error message:
```
{Postgrest.RequestException: no Route matched with those values
   at Postgrest.Helpers.MakeRequest(ClientOptions clientOptions, HttpMethod method, String url, JsonSerializerSettings serializerSettings, Object data, Dictionary`2 headers, CancellationToken cancellationToken)
```

I have no issue with inserting or selecting. Also turned of my policies to test it.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

```
ModeledResponse<Product> response = await Client.From<Product>().Get();
Product model = response.Models.FirstOrDefault();
model.Note = "Test";
ModeledResponse<Product> result = await model.Update<Product>();
```

## Expected behavior

Value should have changed.

## System information

- OS: Windows / Android
- Executing with .Net Maui (.Net 6)
- Version of supabase-csharp: 0.6.2
- Version of postgrest-csharp: 3.0.4

**Comment by acupofjose** [comment]
Thanks for the bug report! Out of curiosity, does doing the following work?

```c#
ModeledResponse<Product> response = await Client.From<Product>().Get();
Product model = response.Models.FirstOrDefault();
model.Note = "Test";
var result = await Client.From<Product>().Update(model);
```

**Comment by Cizzl** [comment]
Thank you, it worked

**Comment by agwanyaseen** [comment]
I am also getting the same error when trying to run the project, with my supabase instance values,

```csharp
var option = new ClientOptions();
option.Headers.Add("apikey", "apikey");
            
var client = new Postgrest.Client("https://<instanceName>.supabase.co", option);
// Get all Users
var users = await client.Table<User>().Get();
```

I even tried making api call, and got the same response
![image](https://user-images.githubusercontent.com/37746694/211987525-459aedaf-5d90-445f-8c69-336964464440.png)

**Comment by acupofjose** [comment]
Ah, if you're going to use just the plain postgrest-csharp client outside of supabase-csharp - you need to specify the REST endpoint [see here for endpoints](https://github.com/supabase-community/supabase-csharp/blob/ad171bd82937ecb84e20a1ec8b6fc90861670618/Supabase/SupabaseOptions.cs#L42-L47):

```c#
var option = new ClientOptions();
option.Headers.Add("apikey", "apikey");
            
var client = new Postgrest.Client("https://<instanceName>.supabase.co/rest/v1", option);
// Get all Users
var users = await client.Table<User>().Get();
```

**Comment by acupofjose** [comment]
@ConnorIllingworth  can you show me what your model looks like?

**Comment by ConnorIllingworth** [comment]
Yes, heres my model

```C#
    [Table("usercategories")]
    public class UserCategory : BaseModel
    {
        [PrimaryKey("id")]
        public Guid Id { get; set; }

        [Column("userid")]
        public Guid UserId { get; set; }

        [Column("created_at")]
        public DateTime CreatedAt { get; set; }

        [Column("sound")]
        public int Sound { get; set; }

        [Column("name")]
        public string Name { get; set; }

        [Column("interval")]
        public string IntervalString { get; set; }
    }
```

**Comment by acupofjose** [comment]
Try setting the following and inserting again please!

```c#
[PrimaryKey("id", false)]
 public Guid Id { get; set; }
```

**Comment by acupofjose** [comment]
Although, `false` will be the default for most use cases… so maybe it’s time to just set that as such in the `PrimaryKey` attribute.
