### ISSUE TITLE
Ignoring `null` in a JSONB column using `record`

### ISSUE THREAD

**Issue by TranquilMarmot** [supabase-community/postgrest-csharp#71]
# Feature request

## Is your feature request related to a problem? Please describe.

I have a JSONB column that I'm writing to, defined like this:

```cs
[Table("games")]
public class Game : BaseModel
{
    [PrimaryKey]
    public string? id { get; set; }

    [Column]
    public GameState? state { get; set; }
}

public record GameState(Boolean? some_value)

// ... elsewhere ...

var data = new GameState(null)l;

await client
    .From<Game>()
    .Where(game => game.id == gameId)
    .Set(game => game.state!, data)
    .Update();
```

This will write the following JSON to the JSONB column:

```json
{ "some_value": null }
```

## Describe the solution you'd like

This is mostly fine, _but_ it would be nice to be able to ignore `null` values when serializing to JSONB.

## Describe alternatives you've considered

I tried to define the column like so:

```cs
    [Column("state", NullValueHandling = NullValueHandling.Ignore)]
    public GameState? state { get; set; }
```

But that doesn't have an effect. I assume because it applies to the entire column, and not the individual fields in the serialized JSON value.

**Comment by acupofjose** [comment]
Sure! You ought to be able to just use the underlying Newtonsoft attribute for it (this is what `ColumnAttribute` is doing behind the scenes anyway). Just specify the property on the object that you want to be ignored.

Something like:
```c#
public record GameState
{
  [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
  public string? ExampleProperty { get; set; }
}
```

**Comment by TranquilMarmot** [comment]
Works perfectly! Thank you!
