### ISSUE TITLE
shouldFilterTopLevel should be changed in documentation

### ISSUE THREAD

**Issue by JonathanVelkeneers** [supabase-community/postgrest-csharp#88]
# Improve documentation

## Link 

[README.MD](https://github.com/supabase-community/postgrest-csharp/blob/master/README.md) and all external sources (like nuget) that have cloned it.

## Describe the problem

`shouldFilterTopLevel` is no longer in the codebase has been renamed as attribute to `useInnerJoin`  [since july 2023](https://github.com/supabase-community/postgrest-csharp/blob/master/CHANGELOG.md#325---2023-07-13). 
The documentation has not been updates to reflect this change.

## Describe the improvement

change `shouldFilterTopLevel: false` to `useInnerJoin: false` in REAMDE.MD

**Comment by acupofjose** [comment]
Thanks for the issue! If you’re interested in doing a PR to adjust it, you’re more than welcome to. Otherwise I’ll adjust the documentation when I’m back at my computer.
