### ISSUE TITLE
Nullable column cant be filtered

### ISSUE THREAD

**Issue by oalpar** [supabase-community/postgrest-csharp#98]
# Bug report

## Describe the bug
Regression of closed issue https://github.com/supabase-community/postgrest-csharp/issues/61
nullable model throws exception when using where/filter clause
## To Reproduce
```
[Table("scenes")]
public class Scene : BaseModel
{
	[PrimaryKey("id")]
	public long Id
	{
		get; set;
	}

	[Column("created_at")]
	public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

	[Column("name")]
	public string Name
	{
		get; set;
	}

	[Column("cluster")]
	public long? Cluster
	{
		get; set;
	}

	[Column("ip")]
	public string Ip
	{
		get; set;
	}

	[Column("port")]
	public int Port
	{
		get; set;
	}

	[Column("is_in_use")]
	public bool IsInUse
	{
		get; set;
	}
	[Column("is_dynamic")]
	public bool IsDynamic
	{
		get; set;
	}


	[Column("tick_rate")]
	public float TickRate
	{
		get; set;
	}
}


 long? cluster = null; //var `reference`
var scene= await _client.Postgrest.Table<Scene>().Where(x => x.Name == SceneName && x.IsDynamic == false && x.cluser==cluster).Single();
```
replicate this statement with a matching entry in the database

## Expected behavior
result is returned

## real behaviour
exception is thrown
![image](https://github.com/supabase-community/postgrest-csharp/assets/38329825/3c33389d-1167-47cf-b059-8d5d3b337fd7)

- version postgres 4.0.3

**Comment by acupofjose** [comment]
Presumably - downgrading to Supabase.Postgrest@4.0.2 fixes your issue?

If so then it looks like our test suite needs to be expanded a bit, because #97 wasn't caught as a regression. That's for the heads up!
